title: Hi there !
author: Aniruddha N N
email: AniruddhaNNalgirkar@eaton.com
description: > 
  Hi there, lets discuss about new way of working!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage...
